-- Database Initialization Script
-- Generated by ProjexLight CLI Export System
-- Project: I want to build app similar
-- Database: postgresql
-- Auto-executed when Docker container is first created
-- Location: ./init-scripts/01-schema.sql
-- Schema Hash: e10808d43975dc40

-- ========================================
-- SCHEMA VERSION TRACKING (For Multi-Developer Sync)
-- ========================================
-- This table tracks the current schema version in your local database.
-- The MCP Schema Sync Agent uses this to detect changes and sync with ProjexLight.

CREATE TABLE IF NOT EXISTS _schema_version (
    id SERIAL PRIMARY KEY,
    schema_hash VARCHAR(64) NOT NULL,
    version INTEGER DEFAULT 1,
    applied_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    source VARCHAR(50) DEFAULT 'init'  -- 'init', 'migration', 'sync'
);

-- ========================================
-- APPLICATION SCHEMA
-- ========================================

-- User-Defined Database Schemas
-- Generated by ProjexLight CLI Export System
-- Database: postgresql
-- Total Schemas: 1

-- ========================================
-- Schema: I want to build app similar Schema
-- Description: Auto-generated database schema for I want to build app similar. Generated from project description...
-- Version: 1
-- ========================================

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email VARCHAR(255),
  password_hash VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE users IS 'Schema: I want to build app similar Schema - Entity: Users';

CREATE TABLE IF NOT EXISTS documents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID,
  file_path VARCHAR(255),
  uploaded_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE documents IS 'Schema: I want to build app similar Schema - Entity: Documents';

CREATE TABLE IF NOT EXISTS signatures (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  document_id UUID,
  signer_email VARCHAR(255),
  status VARCHAR(255) DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE signatures IS 'Schema: I want to build app similar Schema - Entity: Signatures';

CREATE TABLE IF NOT EXISTS user_signatures (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID,
  signature_type VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE user_signatures IS 'Schema: I want to build app similar Schema - Entity: User_signatures';


-- ========================================
-- SAMPLE DATA (Optional)
-- ========================================
-- Uncomment and modify the following to add sample data:

-- INSERT INTO users (column1, column2) VALUES ('value1', 'value2');
-- INSERT INTO documents (column1, column2) VALUES ('value1', 'value2');
-- INSERT INTO signatures (column1, column2) VALUES ('value1', 'value2');
-- INSERT INTO user_signatures (column1, column2) VALUES ('value1', 'value2');

-- ========================================
-- RECORD INITIAL SCHEMA VERSION
-- ========================================
INSERT INTO _schema_version (schema_hash, version, source) VALUES ('e10808d43975dc40', 1, 'init');

-- ========================================
-- SCRIPT COMPLETED
-- ========================================
